apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeapiappweb-deployment
  labels:
    app: freeapiappweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeapiappweb
  template:
    metadata:
      labels:
        app: freeapiappweb 
    spec:
      containers:
      - name: nodeserver
        image: rameshkumarverma/freeapiappweb:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: freeapiappweb-service
spec:
  selector:
    app: freeapiappweb 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
